run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert

issues:
  exclude-dirs:
    - bin
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/
      linters:
        - errcheck
